#!/usr/bin/env python3
"""Embed a raw Saturn ROM dump as a C byte array.

Usage: rom_to_c.py <rom-file> <output.c> [array-name]

Emits a single translation unit with the ROM's raw, unmodified bytes as
a const array plus its length - no nibble-unpacking or other format
transform, since saturn_core's own disk_io.c
(bus_read_nibblesFromFile(), called via getc() in a loop) does that
unpacking itself, unmodified, exactly as it already does when reading
a real file. See firmware/rom_syscalls.c, which serves these same
bytes back to that unmodified vendored code path as though it were a
real file on disk.

The output (roms/rom_images.c by convention) is gitignored - the ROM
it embeds is copyrighted Saturn-family firmware, not ours to
redistribute. See roms/README.md.
"""
import sys


def main() -> int:
    if len( sys.argv ) not in ( 3, 4 ):
        print( f"usage: {sys.argv[0]} <rom-file> <output.c> [array-name]", file=sys.stderr )
        return 2

    rom_path, out_path = sys.argv[ 1 ], sys.argv[ 2 ]
    array_name = sys.argv[ 3 ] if len( sys.argv ) == 4 else "cassini_rom_data"

    with open( rom_path, "rb" ) as f:
        data = f.read()

    with open( out_path, "w" ) as out:
        out.write( f"/* Generated by roms/rom_to_c.py from {rom_path} - do not edit. */\n" )
        out.write( f"const unsigned char {array_name}[] = {{\n" )
        for i in range( 0, len( data ), 16 ):
            chunk = data[ i:i + 16 ]
            out.write( "    " + ", ".join( f"0x{b:02x}" for b in chunk ) + ",\n" )
        out.write( "};\n" )
        out.write( f"const unsigned int {array_name}_len = sizeof({array_name});\n" )

    print( f"wrote {len(data)} bytes as '{array_name}' to {out_path}" )
    return 0


if __name__ == "__main__":
    sys.exit( main() )
