/**
 * @file rom_syscalls.c
 * @brief Newlib syscall overrides serving a compiled-in ROM image as
 * though it were a real file.
 *
 * saturn_core/src/core/disk_io.c's bus_read_nibblesFromFile() (called,
 * unmodified, from romram48.c's RomInit48()) uses only fopen()/getc()/
 * fclose() - no fseek/fread. Rather than touch that vendored call
 * chain, this file overrides the newlib syscalls fopen()/getc()/
 * fclose() are themselves built on: _open()/_read()/_close(), all
 * declared __attribute__((weak)) in
 * ~/pico/pico-sdk/src/rp2_common/pico_clib_interface/newlib_interface.c
 * (confirmed there directly - standard newlib retargeting: a strong
 * definition here cleanly overrides the SDK's weak stub at link time,
 * no duplicate-symbol risk). _fstat()/_lseek() are deliberately left
 * as the SDK's existing weak stubs - fopen()'s fstat-based buffer
 * sizing just falls back to a default size on failure, and
 * bus_read_nibblesFromFile() never calls lseek(); both confirmed
 * harmless to leave unimplemented.
 *
 * Any path other than EMBEDDED_ROM_PATH fails open() outright,
 * exactly matching the "file doesn't exist" experience
 * firmware/saturn_compat/ui4x_compat.c's Resolve() already
 * deliberately creates for every other logical name (ram/port1/
 * port2/...) - see that file's own header comment. Pico-only;
 * deliberately not placed in firmware/saturn_compat/, which stays
 * host-portable (mirrors how soynut keeps Pico-only glue like
 * hp41_persist_flash.c outside emu41gcc_compat/).
 *
 * Also provides _stat() (path-based, distinct from _fstat()): newlib
 * bundles _stat_r together with _fstat_r in the same object file, so
 * referencing the SDK's already-weakly-stubbed _fstat() still pulls
 * in _stat_r's own body, which calls _stat() - a symbol the SDK never
 * stubs at all (only _fstat). Discovered as a real link error, not
 * speculative. Same "fails cleanly" posture as the SDK's own weak
 * _fstat()/_lseek() stubs.
 */

#include <stdbool.h>
#include <string.h>
#include <sys/stat.h>

#include "rom_syscalls.h"

/* Generated by roms/rom_to_c.py from a user-supplied ROM dump - see
 * roms/README.md. Gitignored, never committed. */
extern const unsigned char cassini_rom_data[];
extern const unsigned int cassini_rom_data_len;

#define ROM_FAKE_FD 3

static unsigned int rom_read_pos;
static bool rom_fd_is_open;

int _open( const char* name, int flags, ... )
{
    (void)flags;

    if ( strcmp( name, EMBEDDED_ROM_PATH ) != 0 )
        return -1;

    rom_read_pos = 0;
    rom_fd_is_open = true;
    return ROM_FAKE_FD;
}

int _read( int handle, char* buffer, int length )
{
    if ( handle != ROM_FAKE_FD || !rom_fd_is_open || length < 0 )
        return -1;

    const unsigned int remaining = cassini_rom_data_len - rom_read_pos;
    const unsigned int n = ( unsigned int )length < remaining ? ( unsigned int )length : remaining;

    memcpy( buffer, cassini_rom_data + rom_read_pos, n );
    rom_read_pos += n;

    return ( int )n;
}

int _close( int handle )
{
    if ( handle != ROM_FAKE_FD || !rom_fd_is_open )
        return -1;

    rom_fd_is_open = false;
    return 0;
}

int _stat( const char* path, struct stat* buf )
{
    (void)path;
    (void)buf;
    return -1;
}
